name: Manual trigger
on: 
  workflow_dispatch: 
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    
      -name: Checkout
       uses: actions/checkout@v4.1.0

      -name: Setup Node.js environment
       uses: actions/setup-node@v4.0.0

      -name: Instalar dependencias
       run: npm install

      -name: Ejecutar pruebas
       run: npm cypress run
       
       
         
