name: Manual trigger
on: 
  workflow_dispatch: 
jobs:
  test:
    runs-on: windows-latest
    
    steps:
    
       -name: Checkout
       uses: actions/checkout@v4.1.1

       -name: Setup Node.js environment
       uses: actions/setup-node@v4.0.0
       with:
         node-version: 18.13.0
 
       -name: Instalar dependencias
       run: npm install

       -name: Ejecutar pruebas
        run: npm cypress run
       
       
         
